import logging
from unittest.mock import patch, MagicMock

# Force mocks for heavy ML models so it runs fast and avoids TF errors
import sys
sys.modules['faster_whisper'] = MagicMock()
sys.modules['viral_finder.gemini_transcript_engine'] = MagicMock()
sys.modules['viral_finder.ultron_finder_v33'] = MagicMock()

from viral_finder.orchestrator import _run_staged_pipeline

def mock_transcribe(*args, **kwargs):
    return [
        {"start": 0.0, "end": 2.0, "text": "This is the hook."},
        {"start": 2.0, "end": 5.0, "text": "Nobody knows about it."},
        {"start": 5.0, "end": 10.0, "text": "But the truth is, it changes everything."},
        {"start": 10.0, "end": 15.0, "text": "Here is the payoff."}
    ]

def mock_detect(*args, **kwargs):
    return [
        {"start": 0.0, "end": 5.0, "score": 0.8, "cid": "cand_1", "text": "This is the hook. Nobody knows about it."}
    ]

# Even simpler: Just call the inner stages directly!
from viral_finder.orchestrator import PipelineContext, _run_validation, _run_ranking, _run_arc_assembler, _run_editor_refiner
from viral_finder.intelligence_verifier import reset_verifier

import time
import os

os.environ['HS_ENABLE_ALIGNMENT_SCORING'] = '1'

logging.basicConfig(level=logging.INFO, format="%(message)s")

ctx = PipelineContext(path="dummy.mp4", top_k=1, allow_fallback=False)
ctx.transcript = mock_transcribe()
# Mock an enriched candidate
cand1 = {
    "cid": "cand_1",
    "start": 0.0,
    "end": 5.0,
    "score_enriched": 0.5,
    "signals": {
        "psychology": {"stop_scroll": 0.9, "curiosity": 0.8, "usefulness": 0.85, "completeness": 0.9},
        "semantic": {"impact": 0.7, "meaning": 0.6, "clarity": 0.8},
        "narrative": {"hook_score": 0.9, "trigger_score": 0.8},
        "engagement": {"energy": 0.7, "motion": 0.2}
    },
    "artifacts": {
        "triggers": [
            MagicMock(psychology={"stop_scroll": 0.9, "usefulness": 0.85, "completeness": 0.9}, trigger_type="belief_reversal", confidence=0.9)
        ]
    }
}
ctx.enriched_candidates = [cand1]
ctx.top_k = 1

# Give the candidate some required fields for arc assembler
cand1["text"] = "This is the hook. Nobody knows about it."

# Bypass validation for the test and just feed it to assembler directly
ctx.validated_candidates = [cand1]

print("\n\n" + "="*50)
print("PROVING EXECUTION ORDER (Calling Stages)")
print("="*50)

print("\n--- RUNNING ARC ASSEMBLER (Transform) ---")
_run_arc_assembler(ctx)
if ctx.ranked_output:
    print(f"Arc Assembler Output bounds: {ctx.ranked_output[0]['start']} - {ctx.ranked_output[0]['end']}")

print("\n--- RUNNING RANKING (Judge) ---")
_run_ranking(ctx)
if ctx.final_candidates:
    print(f"Ranking Output bounds: {ctx.final_candidates[0]['start']} - {ctx.final_candidates[0]['end']}")

print("\n--- RUNNING EDITOR REFINER ---")
_run_editor_refiner(ctx)

print("\n\n" + "="*50)
print("PROVING ORPHANED EVIDENCE (Intelligence Verifier)")
print("="*50)

# Run Verifier
v = reset_verifier()
# Register some mock evidence generated by Groq (which is normally done by groq_cortex)
from viral_finder.intelligence_verifier import Evidence, IntelligenceArtifact
v.register_generation(Evidence(origin="groq_surgeon", stage="L6_GROQ_CORTEX", insight_type="usefulness", confidence=0.85, payload={"usefulness": 0.85}, candidate_ref="cand_1"))
v.register_generation(Evidence(origin="groq_surgeon", stage="L6_GROQ_CORTEX", insight_type="completeness", confidence=0.9, payload={"completeness": 0.9}, candidate_ref="cand_1"))
v.register_generation(Evidence(origin="groq_surgeon", stage="L6_GROQ_CORTEX", insight_type="stop_scroll", confidence=0.9, payload={"stop_scroll": 0.9}, candidate_ref="cand_1"))

# Normally bridge marks these consumed.
cand = ctx.final_candidates[0]
if cand["score_breakdown"]["llm_usefulness"] == 0.85:
    v.record_consumption(candidate_ref="cand_1", insight_type="usefulness", consumed_by="L9_RANKING_UVS_MATH")
if cand["score_breakdown"]["llm_completeness"] == 0.9:
    v.record_consumption(candidate_ref="cand_1", insight_type="completeness", consumed_by="L9_RANKING_UVS_MATH")
if cand["score_breakdown"]["llm_stop_scroll"] == 0.9:
    v.record_consumption(candidate_ref="cand_1", insight_type="stop_scroll", consumed_by="L9_RANKING_UVS_MATH")

print(v.render_report())

print("\n\n" + "="*50)
print("PROVING TIMELINE (Final Log)")
print("="*50)

for entry in cand.get("decision_timeline", []):
    print(entry)
