name: Wake HotShort PC

on:
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest

    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect to Tailscale
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Install wakeonlan
        run: sudo apt install wakeonlan -y

      - name: Send Wake Packet
        run: wakeonlan -i 192.168.1.255 30:56:0F:19:9D:1B
